version: '2'
services:
  web:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    links:
      - db
    restart: always
    volumes:
      # Si el SELinux no permite leer el directorio, habilitar con este
      # comando
      # sudo chcon -Rt svirt_sandbox_file_t ~/.dentaljs/media/
      - "${HOME}/.dentaljs/media:/media"

  db:
    image: "mongo:latest"
    restart: always
    volumes:
      # Si el SELinux no permite leer el directorio, habilitar con este
      # comando
      # sudo chcon -Rt svirt_sandbox_file_t ~/.dentaljs/data/db/
      - "${HOME}/.dentaljs/data/db:/data/db"
